# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: 'VS2017-Win2016'
  name: Default

steps:
- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: './.Script/Test-DynamicTask-SyncToGithub-GitOperation.ps1'
    arguments: '-ExcutePSFile "Test-DynamicTask-Main-Continuous.ps1"'
  env:

    GithubPAT: 'f1376f4f317a6510a51286afdc2da1b3dfc9d4f8'

    GithubUserEmail: '503272740@qq.com'

    GithubUserName: 'ChloeQian123'

    GithubRepoName: 'OfficeDocs-Support-pr-Dev'

    AzureUserEmail: 'v-jichlo@microsoft.com'

    AzureUserName: 'Chloe Chloe'



